Fixes to prometheus and grafana deployment

diff --git a/.bluemix/pipeline-grafana.yml b/.bluemix/pipeline-grafana.yml
--- a/.bluemix/pipeline-grafana.yml
+++ b/.bluemix/pipeline-grafana.yml
@@ -113,91 +113,116 @@ stages:
       sed -i 's=$HOST='"$HOST"'=g' $YAML_FILE
       
       # Build the Docker file
-
       echo -e "FROM grafana/grafana:5.2.4\nENV GF_INSTALL_PLUGINS flant-statusmap-panel\nADD dashboardList/dashboardList.yml /etc/grafana/provisioning/dashboards/\nADD config.ini /etc/grafana/\nADD datasource.yml /etc/grafana/provisioning/datasources/\nADD grafanaDashboardConfig/grafanaDashboardConfig.json /var/lib/grafana/dashboards/\nEXPOSE 3000" > Dockerfile
 
-
       echo "REGISTRY_URL=${REGISTRY_URL}"
-            echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
-            echo "IMAGE_NAME=${IMAGE_NAME}"
-            echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
-            echo "DOCKER_ROOT=${DOCKER_ROOT}"
-            echo "DOCKER_FILE=${DOCKER_FILE}"
-            # View build properties
-            if [ -f build.properties ]; then 
-              echo "build.properties:"
-              cat build.properties
-            else 
-              echo "build.properties : not found"
-            fi 
-            # also run 'env' command to find all available env variables
-            # or learn more about the available environment variables at:
-            # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
-            echo "=========================================================="
-            echo "Checking for Dockerfile at the repository root"
-            if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
-            if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=Dockerfile ; fi
-            if [ -f ${DOCKER_ROOT}/${DOCKER_FILE} ]; then 
-              echo -e "Dockerfile found at: ${DOCKER_FILE}"
-            else
-              echo "Dockerfile not found at: ${DOCKER_FILE}"
-              exit 1
-            fi
-            echo "Linting Dockerfile"
-            npm install -g dockerlint
-            dockerlint -f ${DOCKER_ROOT}/${DOCKER_FILE}
-            echo "=========================================================="
-            echo "Checking registry current plan and quota"
-            bx cr plan
-            bx cr quota
-            echo "If needed, discard older images using: bx cr image-rm"
-            echo "Checking registry namespace: ${REGISTRY_NAMESPACE}"
-            NS=$( bx cr namespaces | grep ${REGISTRY_NAMESPACE} ||: )
-            if [ -z "${NS}" ]; then
-              echo "Registry namespace ${REGISTRY_NAMESPACE} not found, creating it."
-              bx cr namespace-add ${REGISTRY_NAMESPACE}
-              echo "Registry namespace ${REGISTRY_NAMESPACE} created."
-            else 
-              echo "Registry namespace ${REGISTRY_NAMESPACE} found."
-            fi
-            echo -e "Existing images in registry"
-            bx cr images --restrict ${REGISTRY_NAMESPACE}
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
+      echo "DOCKER_ROOT=${DOCKER_ROOT}"
+      echo "DOCKER_FILE=${DOCKER_FILE}"
+      
+      # View build properties
+      if [ -f build.properties ]; then 
+        echo "build.properties:"
+        cat build.properties
+      else 
+        echo "build.properties : not found"
+      fi 
+      
+      # also run 'env' command to find all available env variables
+      # or learn more about the available environment variables at:
+      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+      echo "=========================================================="
+      echo "Checking for Dockerfile at the repository root"
+      
+      if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
+      if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=Dockerfile ; fi
+      
+      if [ -f ${DOCKER_ROOT}/${DOCKER_FILE} ]; then 
+        echo -e "Dockerfile found at: ${DOCKER_FILE}"
+      else
+        echo "Dockerfile not found at: ${DOCKER_FILE}"
+        exit 1
+      fi
+      
+      echo "Linting Dockerfile"
+      npm install -g dockerlint
+      dockerlint -f ${DOCKER_ROOT}/${DOCKER_FILE}
+      echo "=========================================================="
+      echo "Checking registry current plan and quota"
+      bx cr plan
+      bx cr quota
+      
+      echo "If needed, discard older images using: bx cr image-rm"
+      echo "Checking registry namespace: ${REGISTRY_NAMESPACE}"
+      NS=$( bx cr namespaces | grep ${REGISTRY_NAMESPACE} ||: )
+      
+      if [ -z "${NS}" ]; then
+        echo "Registry namespace ${REGISTRY_NAMESPACE} not found, creating it."
+        bx cr namespace-add ${REGISTRY_NAMESPACE}
+        echo "Registry namespace ${REGISTRY_NAMESPACE} created."
+      else 
+        echo "Registry namespace ${REGISTRY_NAMESPACE} found."
+      fi
+      
+      echo -e "Existing images in registry"
+      bx cr images --restrict ${REGISTRY_NAMESPACE}
 
+      IMAGE_TAG=${TIMESTAMP}
+      if [ ! -z "${GIT_COMMIT}" ]; then
+        GIT_COMMIT_SHORT=$( echo ${GIT_COMMIT} | head -c 8 ) 
+        IMAGE_TAG=${GIT_COMMIT_SHORT}-${IMAGE_TAG}
+      fi
+      if [ ! -z "${GIT_BRANCH}" ]; then IMAGE_TAG=${GIT_BRANCH}-${IMAGE_TAG} ; fi
+      IMAGE_TAG=${BUILD_NUMBER}-${IMAGE_TAG}
+      
+      echo "=========================================================="
+      echo -e "BUILDING CONTAINER IMAGE: ${IMAGE_NAME}:${IMAGE_TAG}"
+      if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
+      if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=${DOCKER_ROOT}/Dockerfile ; fi
+      
+      set -x
+      bx cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_ROOT} -f ${DOCKER_FILE}
+      set +x
+      bx cr image-inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
+      
+      # Set PIPELINE_IMAGE_URL for subsequent jobs in stage (e.g. Vulnerability Advisor)
+      export PIPELINE_IMAGE_URL="$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG"
+      echo "=========================================================="
+      KEEP=1
+      echo -e "PURGING REGISTRY, only keeping last ${KEEP} image(s) based on image digests"
+      COUNT=0
+      LIST=$( bx cr images --restrict ${REGISTRY_NAMESPACE}/${IMAGE_NAME} --no-trunc --format '__not_implemented__ __not_implemented__@__not_implemented__' | sort -r -u | awk '{print $2}' | sed '$ d' )
+      
+      while read -r IMAGE_URL ; do
+        if [[ "$COUNT" -lt "$KEEP" ]]; then
+          echo "Keeping image digest: ${IMAGE_URL}"
+        else
+          bx cr image-rm "${IMAGE_URL}"
+        fi
+        COUNT=$((COUNT+1)) 
+      done <<< "$LIST"
+      
+      if [[ "$COUNT" -gt 1 ]]; then
+        echo "Content of image registry"
+        bx cr images
+      fi  
 
-            IMAGE_TAG=${TIMESTAMP}
-            if [ ! -z "${GIT_COMMIT}" ]; then
-              GIT_COMMIT_SHORT=$( echo ${GIT_COMMIT} | head -c 8 ) 
-              IMAGE_TAG=${GIT_COMMIT_SHORT}-${IMAGE_TAG}
-            fi
-            if [ ! -z "${GIT_BRANCH}" ]; then IMAGE_TAG=${GIT_BRANCH}-${IMAGE_TAG} ; fi
-            IMAGE_TAG=${BUILD_NUMBER}-${IMAGE_TAG}
-            echo "=========================================================="
-            echo -e "BUILDING CONTAINER IMAGE: ${IMAGE_NAME}:${IMAGE_TAG}"
-            if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
-            if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=${DOCKER_ROOT}/Dockerfile ; fi
-            set -x
-            bx cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_ROOT} -f ${DOCKER_FILE}
-            set +x
-            bx cr image-inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
-            # Set PIPELINE_IMAGE_URL for subsequent jobs in stage (e.g. Vulnerability Advisor)
-            export PIPELINE_IMAGE_URL="$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG"
-            echo "=========================================================="
-            KEEP=1
-            echo -e "PURGING REGISTRY, only keeping last ${KEEP} image(s) based on image digests"
-            COUNT=0
-            LIST=$( bx cr images --restrict ${REGISTRY_NAMESPACE}/${IMAGE_NAME} --no-trunc --format '__not_implemented__ __not_implemented__@__not_implemented__' | sort -r -u | awk '{print $2}' | sed '$ d' )
-            while read -r IMAGE_URL ; do
-              if [[ "$COUNT" -lt "$KEEP" ]]; then
-                echo "Keeping image digest: ${IMAGE_URL}"
-              else
-                bx cr image-rm "${IMAGE_URL}"
-              fi
-              COUNT=$((COUNT+1)) 
-            done <<< "$LIST"
-            if [[ "$COUNT" -gt 1 ]]; then
-              echo "Content of image registry"
-              bx cr images
-            fi  
+      # Changing back to default workdir
+      echo "Change directory to default workdir"
+      cd ..
+
+      # IMAGE information from build.properties is used in Helm Chart deployment to set the release name
+      echo "IMAGE_NAME=${IMAGE_NAME}" >> $ARCHIVE_DIR/build.properties
+      echo "IMAGE_TAG=${IMAGE_TAG}" >> $ARCHIVE_DIR/build.properties
+
+      # REGISTRY information from build.properties is used in Helm Chart deployment to generate cluster secret
+      echo "REGISTRY_URL=${REGISTRY_URL}" >> $ARCHIVE_DIR/build.properties
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}" >> $ARCHIVE_DIR/build.properties
+      echo "GIT_BRANCH=${GIT_BRANCH}" >> $ARCHIVE_DIR/build.properties
+      echo "File 'build.properties' created for passing env variables to subsequent pipeline jobs:"
+      cat $ARCHIVE_DIR/build.properties
 - name: Deploy to IBM Cloud
   inputs:
   - type: job
@@ -226,11 +251,7 @@ stages:
       #!/bin/bash
       # This script checks the IBM Cloud Kubernetes Service cluster is ready, has a namespace configured with access to the private
       # image registry (using an IBM Cloud API Key). It also configures Helm Tiller service to later perform a deploy with Helm.
-      # Input env variables (can be received via a pipeline environment properties.file.
-      echo "IMAGE_NAME=${IMAGE_NAME}"
-      echo "IMAGE_TAG=${IMAGE_TAG}"
-      echo "REGISTRY_URL=${REGISTRY_URL}"
-      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      # Input env variables (can be received via a pipeline environment properties.file.      
       
       # View build properties
       if [ -f build.properties ]; then 
